#!/bin/sh
killall gst-launch-1.0

exec gst-launch-1.0 -vvv filesrc location=./rgbpipe\
         !  rawvideoparse use-sink-caps=false framerate=30/1 width=224 height=224 format=15 \
         ! v4l2h264enc  \
         ! "video/x-h264,profile=baseline,target-bitrate=1024000" \
         ! h264parse ! rtph264pay config-interval=1 mtu=1208 ! "application/x-rtp, payload=(int)96, ssrc=(uint)555555" \
!  udpsink host=127.0.0.1 port=${1}
